### ISSUE TITLE
MS -> ODF Conversion Doesn't Produce Useable Files

### ISSUE THREAD

**Issue by RedSoxFan04** [ertaiNL/multiFormatSave#3]
I used this version of the multiFormatSave extension, and I noticed that it doesn't work too well when going from a Microsoft format to an open format. I converted an Excel spreadsheet and a Word document, both of which I started and continued working on in LibreOffice, but the open-source versions of those documents which were created by multiFormatSave were corrupt. The PDF, RTF, and MSO versions of those documents (created by multiFormatSave) worked fine, but not the open-source format versions.

**Comment by ertaiNL** [comment]
Thanks for letting me know!

I did a simple test and that went well. And I only provide some a easy way to call multiple save-commands at once. But it still should work. So can you provide me with some extra information?

- Can you tell me what version of LibreOffice you use?
- Can you tell me what office-suite and what version the original document was created with?
- Can you provide me with the document / part of the document that gives the error (don't be sorry if you can't for any reason, simply asking because that is the easiest way for me to find what gives an error).
- Can you tell me what version of the extension you use?

**Comment by RedSoxFan04** [comment]
I just realized I made a mistake. It turns out that it's actually multisave that I had a problem with. Shortly after trying multisave, I tried out MultiFormatSave, which works perfectly. I apologize for the confusion I may have caused.

**Comment by ertaiNL** [comment]
no problem. Happy the plugin works.
